routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//--------------Frontend Pages----------------------


Route::get('/','HomeController@index');
Route::get('/product_by_subcategory/{sub_category_id}','HomeController@product_by_subcategory');

Route::get('/product_by_brand/{brand_name}','HomeController@product_by_brand');
Route::get('/product_details/{product_id}','HomeController@product_details');

//----------------Cart Controller------------------------
Route::post('/add_to_cart','CartController@add_to_cart');
Route::get('/show_cart','CartController@show_cart');
Route::get('/delete_to_cart/{id}','CartController@delete_to_cart');
Route::get('/increment_quantity/{id}','CartController@increment_quantity');
Route::get('/decrement_quantity/{id}','CartController@decrement_quantity');



//-------------------Payment by Authorized.Net---------------------------
Route::get('/payment_by_authorize','PaymentByAuthorizeController@index');
Route::post('/payment_complete','PaymentByAuthorizeController@chargeCreditCard');


//-------------------Payment by paypal-------------------------------------
Route::get('/payment_by_paypal','PaymentByPaypalController@index');
Route::post('/paypal_payment','PaymentByPaypalController@paypal');
Route::get('processPaypal','PaymentByPaypalController@returnPaypal')->name('process.paypal');
Route::get('cancelPaypal','PaymentByPaypalController@cancelPaypal')->name('cancel.paypal');




//-----------------Checkout Controller-----------------

Route::get('/login_check','CheckoutController@login_check');
Route::post('/user_registration','CheckoutController@user_registration');
Route::get('/checkout','CheckoutController@checkout');
Route::post('/shipping_details','CheckoutController@shipping_details');
Route::post('/checkout','CheckoutController@store');


//---------------------user Login and Use Logout-----------------
Route::post('/user_login','CheckoutController@user_login');
Route::get('/user_logout','CheckoutController@user_logout');
Route::get('/payment','CheckoutController@payment');
Route::get('/payment_success','CheckoutController@payment_success');
Route::get('/success_done','CheckoutController@success_done');


//--------------------Some Extra Pages Controller----------------------

Route::get('/show_contact','ExtraPagesController@show_contact');
Route::get('/blog','ExtraPagesController@blog_show');

//------------Backend Pages---------------------------

Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin/dashboard','AdminController@dashboard');
Route::get('/show_order_details/{order_id}','AdminController@show_order_details');
Route::get('/admin/invoice/{order_id}','AdminController@invoice');

Route::get('/logout','SuperAdminController@logout');


Route::get('/unactive/{category_id}','StatusController@unactive');
Route::get('/active/{category_id}','StatusController@active');
Route::get('/active_subcategory/{sub_category_id}','StatusController@active_subcategory');
Route::get('/unactive_subcategory/{sub_category_id}','StatusController@unactive_subcategory');

Route::get('/active_product/{product_id}','StatusController@active_product');
Route::get('/unactive_product/{product_id}','StatusController@unactive_product');

Route::get('/unactive_slider/{id}','StatusController@active_slider');
Route::get('/active_slider/{id}','StatusController@unactive_slider');

Route::get('/unactive_brand/{brand_id}','StatusController@active_brand');
Route::get('/active_brand/{brand_id}','StatusController@unactive_brand');

Route::get('/unactive_staff/{id}','StatusController@active_staff');
Route::get('/active_staff/{id}','StatusController@unactive_staff');




Route::get('/show_orderDetails_id/{order_id}','CartController@show_orderDetails_id');

Route::group(['prefix'=>'admin','namespace'=>'admin'],function(){

    
     Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
     Route::resource('category','CategoryController');
     Route::resource('subCategory','SubCategoryController');
     Route::resource('products','ProductController');
     Route::resource('slider','SliderController');
     Route::resource('brand','BrandController');
     Route::resource('blog','BlogController');
     Route::resource('staff','StaffController');
     Route::resource('manage_order','ManageOrderController');
     Route::resource('manage_payment','ManagePaymentController');

    


});

app/Http/Controllers/Admin/SubCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use DB;
use App\Http\Controllers\Controller;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()

    {
        
        $sub_categories=DB::table('tbl_sub_category')
                     ->join('tbl_category','tbl_sub_category.category_id','=','tbl_category.category_id')
                     ->select('tbl_sub_category.*','tbl_category.category_name')
                     
                     ->get();

       return view ('admin.subCategory.index',compact('sub_categories'));

        //print_r($sub_categories);             
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = DB::table('tbl_category')->get();
        return view ('admin.subCategory.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[

             'sub_category_name' => 'required',
             'sub_category_description' => 'required',
             'publication_status' => 'required',
        ]);

        $data=array();

        $data['sub_category_id']=$request->sub_category_id;
        $data['category_id']=$request->category_id;
        $data['sub_category_name']=$request->sub_category_name;
        $data['sub_category_description']=$request->sub_category_description;
        $data['publication_status']=$request->publication_status;
 
    DB::table('tbl_sub_category')->insert($data);
    return redirect()->route('subCategory.index')->with('successMsg','Data Added Successfully !');
     
    }

    
    



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($sub_category_id)
    {
       $sub_categories=DB::table('tbl_sub_category')
                      ->join('tbl_category','tbl_sub_category.category_id','=','tbl_category.category_id')
                      ->where('sub_category_id',$sub_category_id)
                      ->first();    
    
        return view('admin.subCategory.edit',compact('sub_categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $sub_category_id)
    {
        $this->validate($request,[

             'sub_category_name' => 'required',
             'sub_category_description' => 'required',
        ]);

        $data = array();

        $data['category_id']=$request->category_id;
        $data['sub_category_name']=$request->sub_category_name;
        $data['sub_category_description']=$request->sub_category_description;

            DB::table('tbl_sub_category')
                    ->where('sub_category_id',$sub_category_id)
                    ->update($data);
             
             return redirect()->route('subCategory.index')->wuth('successMsg','Data Updated Successfully!!');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($sub_category_id)
    {
        DB::table('tbl_sub_category')
               ->where('sub_category_id',$sub_category_id)
               ->delete();
        return redirect()->back()->with('successMsg','Data Deleated Successfully!!');
    }
}

resources/views/admin/subCategory/create.blade.php
@extends('layouts.app')

@section('title','Add Sub Category')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add New Sub Category</li>
      </ol>
</section> 

<section class="content">
<div class="row">
        <div class="col-md-12">
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Add New Sub Category</h3>
              @if($errors->any())
                  @foreach($errors->all() as $error)
                     <div class="alert alert-danger alert-dismissible" role="alert">
                      <strong>Danger!</strong> - {{$error}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  @endforeach
              @endif

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
               
                <button type="button" class="btn btn-box-tool" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                              
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
         <form class="form-horizontal" action="{{route('subCategory.store')}}" method="POST">
         	@csrf

            <div class="box-body">
              <div class="row">
                 <div class="col-md-8">


                 	    <div class="form-group">
		                  <label for="Subcategory Name" class="col-sm-4 control-label"> Category Name</label>

		                  <div class="col-sm-8">
                        
		                   <select class="form-control" id="sel1" name="category_id">
								<option>---Select Menu---</option>
						@foreach($categories as $key=>$category)		
								<option value="{{$category->category_id}}">{{$category->category_name}}</option>
						@endforeach		
							</select>
                        
		                  </div>
		                </div>
                 		
                 		<div class="form-group">
		                  <label for="sub_category_name" class="col-sm-4 control-label">Sub Category Name</label>

		                  <div class="col-sm-8">
		                    <input type="text" class="form-control" id="category_name" placeholder="Enter Sub Category Name" name="sub_category_name">
		                  </div>
		                </div>

		          
		                <div class="form-group hidden-phone">
		                  <label for="category_description" class="col-sm-4 control-label">Sub Category Description</label>

		                  <div class="col-sm-8">
		                      <textarea class="textarea" name="sub_category_description" placeholder="Place some text here"
                          style="width: 100%; height: 140px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
                          	
                             </textarea>
		                  </div>
		                </div>

		                <div class="form-group">
		                  <label for="publication_status" class="col-sm-4 control-label">Publication Status</label>

		                  <div class="col-sm-8">
		                    <input type="checkbox" name="publication_status" value="1">
		                  </div>
		                </div>
                 		
                 	
                 </div>
               
             </div>
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row">
                <div class="col-md-8">
                	<button type="submit" class="btn btn-primary pull-right">Submit
                	</button>

                	<button type="reset" class="btn btn-default"> Cancel
                	</button>
                	
                </div>
                            
              </div>
              <!-- /.row -->
            </div>
        </form> 
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>

  </section> 


@endsection

resources/views/admin/subCategory/edit.blade.php
@extends('layouts.app')

@section('title','Edit Subcategory')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit Sub Category</li>
      </ol>
</section> 

<section class="content">
<div class="row">
        <div class="col-md-12">
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Sub Category</h3>
              @if($errors->any())
                  @foreach($errors->all() as $error)
                     <div class="alert alert-danger alert-dismissible" role="alert">
                      <strong>Danger!</strong> - {{$error}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  @endforeach
              @endif

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
               
                <button type="button" class="btn btn-box-tool" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                              
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
         <form class="form-horizontal" action="{{route('subCategory.update',$sub_categories->sub_category_id)}}" method="POST">
         	@csrf
         	@method('put')

            <div class="box-body">
              <div class="row">
                 <div class="col-md-8">


                 	    <div class="form-group">
		                  <label for="Subcategory Name" class="col-sm-4 control-label"> Category Name</label>

		                  <div class="col-sm-8">
                        
		                   <select class="form-control" id="sel1" name="category_id">
								<option value="{{$sub_categories->category_id}}">{{$sub_categories->category_name}}</option>

						    <?php 
                                $categories=DB::table('tbl_category')
                                         ->where('publication_status',1)
                                         ->get();
                             foreach($categories as $key=>$category) {           
						    ?>
								<option value="{{$category->category_id}}">{{$category->category_name}}</option>
						    <?php }?>
							</select>
                        
		                  </div>
		                </div>
                 		
                 		<div class="form-group">
		                  <label for="sub_category_name" class="col-sm-4 control-label">Sub Category Name</label>

		                  <div class="col-sm-8">
		                    <input type="text" class="form-control" id="sub_category_name" name="sub_category_name" value="{{$sub_categories->sub_category_name}}">
		                  </div>
		                </div>

		          
		                <div class="form-group hidden-phone">
		                  <label for="category_description" class="col-sm-4 control-label">Sub Category Description</label>

		                  <div class="col-sm-8">
		                      <textarea class="textarea" name="sub_category_description" placeholder="Place some text here"
                          style="width: 100%; height: 140px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{$sub_categories->sub_category_description}}
                             </textarea>
		                  </div>
		                </div>
                	
                 </div>
               
             </div>
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row">
                <div class="col-md-8">
                	<button type="submit" class="btn btn-primary pull-right">Update
                	</button>

                	<button type="reset" class="btn btn-default"> Cancel
                	</button>
                	
                </div>
                            
              </div>
              <!-- /.row -->
            </div>
        </form> 
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>

  </section> 

@endsection

resources/views/admin/subCategory/index.blade.php
@extends('layouts.app')

@section('title','All Subcategory')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-list"> </i> All Subcategory</li>
      </ol>
</section> 

<section class="content">
	<div class="row">
		<div class="col-xs-12">

			<div class="box box-success">
				<div class="box-header">
					<h3 class="box-title">Subcategory List</h3>
				</div>

				@if(session('successMsg'))

		         <div class="alert alert-success alert-dismissible" role="alert">		    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		          </button>
		            <span>Success - {{session('successMsg')}}</span>
		         </div> 
		        @endif

				<div class="box-body">
					<table id="example2" class="table table-bordered table-hover table-responsive">
						<thead>
						  <tr>
						    <th>Subcategory Id</th>
						    <th>Subcategory Name</th>
						    <th>Category Name</th>
						    <th>Subcategory Description</th>
						    <th>Status</th>
						    <th>Action</th>
						  </tr>
						</thead>
						<tbody>
					@foreach($sub_categories as $key=>$sub_category) 		
						  <tr>
						 	
						    <td>{{$sub_category->sub_category_id}}</td>
						    <td>{{$sub_category->sub_category_name}}</td>
						    <td>{{$sub_category->category_name}}</td>
						    <td>{{$sub_category->sub_category_description}}</td>
						    <td>
						    	@if($sub_category->publication_status==1)
						    	<span class="label label-success">Active</span>
						    	@else
                                <span class="label label-danger">Unactive</span>
                                @endif
						    </td>
						    <td>
                                @if($sub_category->publication_status==1)

						    	<a href="{{URL::to('/unactive_subcategory/'.$sub_category->sub_category_id)}}" class="btn btn-danger btn-sm"><i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
						    	@else
						    	<a href="{{URL::to('/active_subcategory/'.$sub_category->sub_category_id)}}" class="btn btn-success btn-sm"><i class="fa fa-thumbs-up" aria-hidden="true"></i></a>
						    	@endif

						    	<a href="{{route('subCategory.edit',$sub_category->sub_category_id)}}" class="btn btn-info btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

						    	<form id="delete-form-{{$sub_category->sub_category_id}}"action="{{route('subCategory.destroy',$sub_category->sub_category_id)}}" method="POST" style="display:none">
						    		@csrf
						    		@method('DELETE')
						    		
						    	</form>
						    	<button class="btn btn-danger btn-sm" onclick="if(confirm('! Are You Sure You Want to Delete This Record ?')){
						    		event.preventDefault();
						    		document.getElementById('delete-form-{{$sub_category->sub_category_id}}'
						    			).submit();
						    	}else{

						    		event.preventDefault();
						    	}

						    	"><i class="fa fa-trash" aria-hidden="true"></i></button>
						    </td>
						
						  </tr>
					@endforeach
						</tbody>
					</table>
				</div>
			</div>
			
		</div>
	</div>
</section>




@endsection

@push('scripts')

<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

@endpush