routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//--------------Frontend Pages----------------------


Route::get('/','HomeController@index');
Route::get('/product_by_subcategory/{sub_category_id}','HomeController@product_by_subcategory');

Route::get('/product_by_brand/{brand_name}','HomeController@product_by_brand');
Route::get('/product_details/{product_id}','HomeController@product_details');

//----------------Cart Controller------------------------
Route::post('/add_to_cart','CartController@add_to_cart');
Route::get('/show_cart','CartController@show_cart');
Route::get('/delete_to_cart/{id}','CartController@delete_to_cart');
Route::get('/increment_quantity/{id}','CartController@increment_quantity');
Route::get('/decrement_quantity/{id}','CartController@decrement_quantity');



//-------------------Payment by Authorized.Net---------------------------
Route::get('/payment_by_authorize','PaymentByAuthorizeController@index');
Route::post('/payment_complete','PaymentByAuthorizeController@chargeCreditCard');


//-------------------Payment by paypal-------------------------------------
Route::get('/payment_by_paypal','PaymentByPaypalController@index');
Route::post('/paypal_payment','PaymentByPaypalController@paypal');
Route::get('processPaypal','PaymentByPaypalController@returnPaypal')->name('process.paypal');
Route::get('cancelPaypal','PaymentByPaypalController@cancelPaypal')->name('cancel.paypal');




//-----------------Checkout Controller-----------------

Route::get('/login_check','CheckoutController@login_check');
Route::post('/user_registration','CheckoutController@user_registration');
Route::get('/checkout','CheckoutController@checkout');
Route::post('/shipping_details','CheckoutController@shipping_details');
Route::post('/checkout','CheckoutController@store');


//---------------------user Login and Use Logout-----------------
Route::post('/user_login','CheckoutController@user_login');
Route::get('/user_logout','CheckoutController@user_logout');
Route::get('/payment','CheckoutController@payment');
Route::get('/payment_success','CheckoutController@payment_success');
Route::get('/success_done','CheckoutController@success_done');


//--------------------Some Extra Pages Controller----------------------

Route::get('/show_contact','ExtraPagesController@show_contact');
Route::get('/blog','ExtraPagesController@blog_show');

//------------Backend Pages---------------------------

Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin/dashboard','AdminController@dashboard');
Route::get('/show_order_details/{order_id}','AdminController@show_order_details');
Route::get('/admin/invoice/{order_id}','AdminController@invoice');

Route::get('/logout','SuperAdminController@logout');


Route::get('/unactive/{category_id}','StatusController@unactive');
Route::get('/active/{category_id}','StatusController@active');
Route::get('/active_subcategory/{sub_category_id}','StatusController@active_subcategory');
Route::get('/unactive_subcategory/{sub_category_id}','StatusController@unactive_subcategory');

Route::get('/active_product/{product_id}','StatusController@active_product');
Route::get('/unactive_product/{product_id}','StatusController@unactive_product');

Route::get('/unactive_slider/{id}','StatusController@active_slider');
Route::get('/active_slider/{id}','StatusController@unactive_slider');

Route::get('/unactive_brand/{brand_id}','StatusController@active_brand');
Route::get('/active_brand/{brand_id}','StatusController@unactive_brand');

Route::get('/unactive_staff/{id}','StatusController@active_staff');
Route::get('/active_staff/{id}','StatusController@unactive_staff');




Route::get('/show_orderDetails_id/{order_id}','CartController@show_orderDetails_id');

Route::group(['prefix'=>'admin','namespace'=>'admin'],function(){

    
     Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
     Route::resource('category','CategoryController');
     Route::resource('subCategory','SubCategoryController');
     Route::resource('products','ProductController');
     Route::resource('slider','SliderController');
     Route::resource('brand','BrandController');
     Route::resource('blog','BlogController');
     Route::resource('staff','StaffController');
     Route::resource('manage_order','ManageOrderController');
     Route::resource('manage_payment','ManagePaymentController');

    


});

app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands=DB::table('tbl_brand')->get();

        return view ('admin.brand.index',compact('brands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[

             'brand_name'=>'required',
             'brand_description'=>'required',
             'publication_status'=>'required',        
        ]);

        $data=array();

        //$data['brand_id']=$request->brand_id;
        $data['brand_name']=$request->brand_name;
        $data['brand_description']=$request->brand_description;
        $data['publication_status']=$request->publication_status;

        DB::table('tbl_brand')->insert($data);
        return redirect()->route('brand.index')->with('successMsg','Data Inserted Successfully');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($brand_id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($brand_id)
    {
        $brands=DB::table('tbl_brand')
                   ->where('brand_id',$brand_id)
                   ->first();
      return view('admin.brand.edit',compact('brands'));             
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $brand_id)
    {
       
        $this->validate($request,[
            
            'brand_name'=>'required',
            'brand_description'=>'required',

        ]);

        $data=array();

        $data['brand_name']=$request->brand_name;
        $data['brand_description']=$request->brand_description;
        

        DB::table('tbl_brand')
                ->where('brand_id',$brand_id)
                ->update($data);

        return redirect()->route('brand.index')->with('successMsg','Data Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($brand_id)
    {
        DB::table('tbl_brand')
               ->where('brand_id',$brand_id)
               ->delete();
        return redirect()->back()->with('successMsg','Data Deleted Successfully');
    }
}

resources/views/admin/brand/create.blade.php
@extends('layouts.app')

@section('title','Add Brand')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add New Brand</li>
      </ol>
</section>  

<section class="content">
<div class="row">
        <div class="col-md-12">
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Add New Brand</h3>
              @if($errors->any())
                  @foreach($errors->all() as $error)
                     <div class="alert alert-danger alert-dismissible" role="alert">
                      <strong>Danger!</strong> - {{$error}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  @endforeach
              @endif

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
               
                <button type="button" class="btn btn-box-tool" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                              
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
         <form class="form-horizontal" action="{{route('brand.store')}}" method="POST">
         	@csrf

            <div class="box-body">
              <div class="row">
                 <div class="col-md-8">
                 	
                 		
                 		<div class="form-group">
		                  <label for="Brand Name" class="col-sm-4 control-label">Brand Name</label>

		                  <div class="col-sm-8">
		                    <input type="text" class="form-control" placeholder="Enter Brand Name " name="brand_name">
		                  </div>
		                </div>

		                <div class="form-group hidden-phone">
		                  <label for="Brand Description" class="col-sm-4 control-label">Brand Description</label>

		                  <div class="col-sm-8">
		                      <textarea class="textarea" name="brand_description" 
                          style="width: 100%; height: 140px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
                          	
                             </textarea>
		                  </div>
		                </div>

		                <div class="form-group">
		                  <label for="publication_status" class="col-sm-4 control-label">Publication Status</label>

		                  <div class="col-sm-8">
		                    <input type="checkbox" name="publication_status" value="1">
		                  </div>
		                </div>
                 		
                 	
                 </div>
               
             </div>
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row">
                <div class="col-md-8">
                	<button type="submit" class="btn btn-primary pull-right">Submit
                	</button>

                	<button type="reset" class="btn btn-default"> Cancel
                	</button>
                	
                </div>
                            
              </div>
              <!-- /.row -->
            </div>
        </form> 
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>

  </section> 

@endsection

resources/views/admin/brand/edit.blade.php
@extends('layouts.app')

@section('title','Update category')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Update Category</li>
      </ol>
</section> 

<section class="content">
<div class="row">
        <div class="col-md-12">
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Add New Category</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
               
                <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                              
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
         <form class="form-horizontal" action="{{route('brand.update',$brands->brand_id)}}" method="POST">
         	@csrf
         	@method('put')

            <div class="box-body">
              <div class="row">
                 <div class="col-md-8">
                 	
                 		
                 		<div class="form-group">
		                  <label for="Brand Name" class="col-sm-4 control-label">Brand Name</label>

		                  <div class="col-sm-8">
		                    <input type="text" class="form-control" id="brand_name"  name="brand_name" value="{{$brands->brand_name}}">
		                  </div>
		                </div>

		                <div class="form-group hidden-phone">
		                  <label for="Brand Description" class="col-sm-4 control-label">Brand Description</label>

		                  <div class="col-sm-8">
		                      <textarea class="textarea" name="brand_description"
                          style="width: 100%; height: 140px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{$brands->brand_description}}

                          	    
                             </textarea>
		                  </div>
		                </div>		                
                	
                 </div>
               
             </div>
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row">
                <div class="col-md-8">
                	<button type="submit" class="btn btn-primary pull-right">Update
                	</button>

                	<button type="reset" class="btn btn-default"> Cancel
                	</button>
                	
                </div>
                            
              </div>
              <!-- /.row -->
            </div>
        </form> 
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>

  </section>  

@endsection

resources/views/admin/brand/index.blade.php
@extends('layouts.app')

@section('title','Brand')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-list"> </i> All Brand</li>
      </ol>
</section>  

<section class="content">
      <div class="row">
        <div class="col-xs-12">
          
            <!-- /.box-header -->           
          <div class="box box-success">
            <div class="box-header">
              <h3 class="box-title">Brand List</h3>
            </div>

         @if(session('successMsg'))

         <div class="alert alert-success alert-dismissible" role="alert">                   
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
            <span>Success - {{session('successMsg')}}</span>
         </div> 
         @endif

            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped table-responsive">
                <thead>
                <tr>
                  <th>Brand ID</th>
                  <th>Brand Name</th>
                  <th>Brand Description</th>
                  <th>Status</th>
                  <th class="pull-right">Action</th>
                </tr>
                </thead>
                <tbody>
               @foreach($brands as $brand) 	
                <tr>
                  <td>{{$brand->brand_id}}</td>
                  <td>{{$brand->brand_name}}</td>
                  <td>{{$brand->brand_description}}</td>
                  <td>

                  @if($brand->publication_status==1)
                  <span class="label label-success">Active</span>
                  @else
                  <span class="label label-danger">Unactive</span>
                  @endif
                  </td>
                  <td class="pull-right">
                   
                   @if($brand->publication_status==1)
                  	<a class="btn btn-danger btn-sm" href="{{URL::to('/unactive_brand/'.$brand->brand_id)}}"><i class="fa fa-thumbs-down" aria-hidden="true"></i>
                  	</a>
                  	@else
                  	<a class="btn btn-success btn-sm" href="{{URL::to('/active_brand/'.$brand->brand_id)}}"><i class="fa fa-thumbs-up" aria-hidden="true"></i>
                  	</a>
                  	@endif

                  	<a class="btn btn-info btn-sm" href="{{route('brand.edit',$brand->brand_id)}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  	</a>

                    <form id="delete-form-{{$brand->brand_id}}" action="{{route('brand.destroy',$brand->brand_id)}}" method="POST" style="display:none">
                      @csrf
                      @method('DELETE')
                      
                    </form>

                  	<button class="btn btn-danger btn-sm"
                    onclick="if(confirm('Are You Sure You Want to Delete This')){
                        event.preventDefault();
                         document.getElementById('delete-form-{{$brand->brand_id}}').submit();
                    }else{
                           event.preventDefault();
                    }
                    ">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                  </td>
                </tr> 
                @endforeach                             
                </tbody>
               
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>

@endsection


@push('scripts')

<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

@endpush