routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//--------------Frontend Pages----------------------


Route::get('/','HomeController@index');
Route::get('/product_by_subcategory/{sub_category_id}','HomeController@product_by_subcategory');

Route::get('/product_by_brand/{brand_name}','HomeController@product_by_brand');
Route::get('/product_details/{product_id}','HomeController@product_details');

//----------------Cart Controller------------------------
Route::post('/add_to_cart','CartController@add_to_cart');
Route::get('/show_cart','CartController@show_cart');
Route::get('/delete_to_cart/{id}','CartController@delete_to_cart');
Route::get('/increment_quantity/{id}','CartController@increment_quantity');
Route::get('/decrement_quantity/{id}','CartController@decrement_quantity');



//-------------------Payment by Authorized.Net---------------------------
Route::get('/payment_by_authorize','PaymentByAuthorizeController@index');
Route::post('/payment_complete','PaymentByAuthorizeController@chargeCreditCard');


//-------------------Payment by paypal-------------------------------------
Route::get('/payment_by_paypal','PaymentByPaypalController@index');
Route::post('/paypal_payment','PaymentByPaypalController@paypal');
Route::get('processPaypal','PaymentByPaypalController@returnPaypal')->name('process.paypal');
Route::get('cancelPaypal','PaymentByPaypalController@cancelPaypal')->name('cancel.paypal');




//-----------------Checkout Controller-----------------

Route::get('/login_check','CheckoutController@login_check');
Route::post('/user_registration','CheckoutController@user_registration');
Route::get('/checkout','CheckoutController@checkout');
Route::post('/shipping_details','CheckoutController@shipping_details');
Route::post('/checkout','CheckoutController@store');


//---------------------user Login and Use Logout-----------------
Route::post('/user_login','CheckoutController@user_login');
Route::get('/user_logout','CheckoutController@user_logout');
Route::get('/payment','CheckoutController@payment');
Route::get('/payment_success','CheckoutController@payment_success');
Route::get('/success_done','CheckoutController@success_done');


//--------------------Some Extra Pages Controller----------------------

Route::get('/show_contact','ExtraPagesController@show_contact');
Route::get('/blog','ExtraPagesController@blog_show');

//------------Backend Pages---------------------------

Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin/dashboard','AdminController@dashboard');
Route::get('/show_order_details/{order_id}','AdminController@show_order_details');
Route::get('/admin/invoice/{order_id}','AdminController@invoice');

Route::get('/logout','SuperAdminController@logout');


Route::get('/unactive/{category_id}','StatusController@unactive');
Route::get('/active/{category_id}','StatusController@active');
Route::get('/active_subcategory/{sub_category_id}','StatusController@active_subcategory');
Route::get('/unactive_subcategory/{sub_category_id}','StatusController@unactive_subcategory');

Route::get('/active_product/{product_id}','StatusController@active_product');
Route::get('/unactive_product/{product_id}','StatusController@unactive_product');

Route::get('/unactive_slider/{id}','StatusController@active_slider');
Route::get('/active_slider/{id}','StatusController@unactive_slider');

Route::get('/unactive_brand/{brand_id}','StatusController@active_brand');
Route::get('/active_brand/{brand_id}','StatusController@unactive_brand');

Route::get('/unactive_staff/{id}','StatusController@active_staff');
Route::get('/active_staff/{id}','StatusController@unactive_staff');




Route::get('/show_orderDetails_id/{order_id}','CartController@show_orderDetails_id');

Route::group(['prefix'=>'admin','namespace'=>'admin'],function(){

    
     Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
     Route::resource('category','CategoryController');
     Route::resource('subCategory','SubCategoryController');
     Route::resource('products','ProductController');
     Route::resource('slider','SliderController');
     Route::resource('brand','BrandController');
     Route::resource('blog','BlogController');
     Route::resource('staff','StaffController');
     Route::resource('manage_order','ManageOrderController');
     Route::resource('manage_payment','ManagePaymentController');

    


});

resources/views/admin/change_order_status.blade.php
@extends('layouts.app')
@section('title','Change Order Status')

@section('content')

<section class="content-header">
      <h1>Dashboard<small>Control panel</small></h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i><strong> Home</strong></a></li>
        <li class="active"><i class="fa fa-user-circle-o" aria-hidden="true"> </i><strong> Change Status</strong></li>
      </ol>
</section>

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-success">
				<div class="box-header with-border">
					<h3 class="box-title"><i class="fa fa-list" aria-hidden="true"> </i> Change Order Status</h3>
				</div>              

		<form class="form-horizontal" action="{{route('manage_order.update',$orders->order_id)}}" method="POST">
         @csrf
         @method('PUT')

            <div class="box-body">
              <div class="row">
                 <div class="col-md-8">
                                  		
             		<div class="form-group">
	                  <label for="Order Status" class="col-sm-4 control-label">Order Status</label>

	                  <div class="col-sm-8">
	                    
		                    <select class="form-control" id="sel1" name="status">
		                    	<option value="{{$orders->status}}">  
                                    @if($orders->status == 0)
                                 <span class="label label-warning">Pending</span>
                                    @elseif($orders->status == 1)
                                 <span class="label label-info">Processing</span>
                                    @else
                                 <span class="label label-danger">Delivered</span>
                                    @endif

		                    	</option>
							    <option value="0"> Pending </option>
							    <option value="1"> Processing</option>
							    <option value="2"> Delivered</option>
							    
							</select>
	                  </div>
	                </div>
	                                 	
                 </div>
               
             </div>
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row">
                <div class="col-md-8">
                	<button type="submit" class="btn btn-primary pull-right">Submit
                	</button>

                	<button type="reset" class="btn btn-default"> Cancel
                	</button>
                	
                </div>
                            
              </div>
              <!-- /.row -->
            </div>
        </form> 

			</div>
		</div>

		
	</div>
	
</section>

@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.app')
@section('title','Dashboard')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
      </ol>
</section>   

<section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">CPU Traffic</span>
              <span class="info-box-number">90<small>%</small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>

        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-product-hunt" aria-hidden="true"></i></span>
            <?php 
               $product=0;
               $product=DB::table('tbl_products')->count();

             ?>

            <div class="info-box-content">
              <span class="info-box-text">Total Products</span>
              <span class="info-box-number">{{$product}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>

        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span>
            <?php 
                $total=0;
                $orders=DB::table('tbl_orders')->get();
                foreach($orders as $order){
                  $total += $order->quantity;               
               }
               /*echo $total;*/
             ?>

            <div class="info-box-content">
              <span class="info-box-text">Sales</span>
              <span class="info-box-number">{{$total}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-user-circle-o" aria-hidden="true"></i></span>
            <?php 
                $customer=0;
                $customer=DB::table('tbl_customers')->count();
                 
             ?>

            <div class="info-box-content">
              <span class="info-box-text">Customers</span>
              <span class="info-box-number">{{$customer}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-money" aria-hidden="true"></i></span>
            <?php 
              $amount=0;
              $orders=DB::table('tbl_orders')->get();
              foreach($orders as $order){
                  $amount += $order->total_amount;
              }

             ?>

            <div class="info-box-content">
              <span class="info-box-text">Total Revenue</span>
              <span class="info-box-number">{{$amount}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>

      </div>
      <!-- /.row -->



      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Monthly Recap Report</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-8">
                 
                  <!-- /.chart-responsive -->
                </div>
                <!-- /.col -->
                <div class="col-md-4">
                  <p class="text-center">
                    <strong>Goal Completion</strong>
                  </p>
                  
                </div>

                
              </div>
              
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row">
                <div class="col-sm-3 col-xs-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                    <h5 class="description-header">$35,210.43</h5>
                    <span class="description-text">TOTAL REVENUE</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-xs-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                    <h5 class="description-header">$10,390.90</h5>
                    <span class="description-text">TOTAL COST</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-xs-6">
                  <div class="description-block border-right">
                    <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                    <h5 class="description-header">$24,813.53</h5>
                    <span class="description-text">TOTAL PROFIT</span>
                  </div>
                  <!-- /.description-block -->
                </div>
                <!-- /.col -->
                <div class="col-sm-3 col-xs-6">
                  <div class="description-block">
                    <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                    <h5 class="description-header">1200</h5>
                    <span class="description-text">GOAL COMPLETIONS</span>
                  </div>
                  <!-- /.description-block -->
                </div>
              </div>
              <!-- /.row -->
            </div>
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <div class="col-md-8">
          <!-- MAP & BOX PANE -->
          
     
          <div class="row">
          
          </div>
   

          <!-- TABLE: LATEST ORDERS -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title"><strong>Product Sell Summary</strong></h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">
                <table id="example1" class="table no-margin">

               <?php   
                    $products=DB::table('tbl_products')->get();
                                   
                ?>

                  <thead>
                  <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Image</th>
                    <th>Number of Sales</th>
                  </tr>
                  </thead>
                  <tbody>
              @foreach($products as $product)

                <?php 

                     $orders=DB::table('tbl_order_details')
                         ->where('product_id',$product->product_id)
                         ->count();

                 ?>
                  <tr>
                    <td>{{$product->product_id}}</td>
                    <td>{{$product->product_name}}</td>
                    <td><img src="{{URL::to($product->product_image)}}" style="width:50px; height:50px;"></td>
                    <td>{{$orders}}</td>
                  </tr>
              @endforeach
                 
                               
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
            <!-- /.box-body -->
            <!-- <div class="box-footer clearfix">
              <a href="javascript:void(0)" class="btn btn-sm btn-info btn-flat pull-left">Place New Order</a>
              <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
            </div> -->
            <!-- /.box-footer -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->

        <div class="col-md-4">
          <!-- Info Boxes Style 2 -->
          <div class="info-box bg-yellow">
            <span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Inventory</span>
              <span class="info-box-number">5,200</span>

              <div class="progress">
                <div class="progress-bar" style="width: 50%"></div>
              </div>
              <span class="progress-description">
                    50% Increase in 30 Days
                  </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
          <div class="info-box bg-green">
            <span class="info-box-icon"><i class="ion ion-ios-heart-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Mentions</span>
              <span class="info-box-number">92,050</span>

              <div class="progress">
                <div class="progress-bar" style="width: 20%"></div>
              </div>
              <span class="progress-description">
                    20% Increase in 30 Days
                  </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
          <div class="info-box bg-red">
            <span class="info-box-icon"><i class="ion ion-ios-cloud-download-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Downloads</span>
              <span class="info-box-number">114,381</span>

              <div class="progress">
                <div class="progress-bar" style="width: 70%"></div>
              </div>
              <span class="progress-description">
                    70% Increase in 30 Days
                  </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
          <div class="info-box bg-aqua">
            <span class="info-box-icon"><i class="ion-ios-chatbubble-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Direct Messages</span>
              <span class="info-box-number">163,921</span>

              <div class="progress">
                <div class="progress-bar" style="width: 40%"></div>
              </div>
              <span class="progress-description">
                    40% Increase in 30 Days
                  </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->

          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Browser Usage</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              
              <!-- /.row -->
            </div>
            
          </div>
          <!-- /.box -->

          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>

@endsection

@push('scripts')

<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

@endpush

resources/views/admin/invoice.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Invoice</title>
	
</head>
<style>
	.top{
		background-color: #D7D4F7;
	}
	.top p{
        line-height: 10px;
        /* float: right; */
        font-family: initial;
        font-weight: bold;
	}
	
</style>
<body>
	<div class="container">
		<div class="top">
			<div class="row">
				<div class="col-md-8">
					<img src="{{URL::to('frontend/images/home/logo.png')}}" alt="" style="height:70px;height: 70px;padding: 4px 10px;margin: 30px 2px;">
				</div>
				<div class="col-md-4">
					<h2>E-Shopper Ecommerce</h2>
					<p>House# 13 Road# 09 Sector# 10</p>
					<p>Uttara Dhaka-1230</p>
					<p>Phone: +8801749386163</p>
					<p>Email: query@e-shopper.com</p>
					<br>
				</div>
			</div>
		</div>
		
	</div>
	
</body>
</html>

resources/views/admin/manage_order.blade.php
@extends('layouts.app')
@section('title','Manage Order')

@section('content')

<section class="content-header">
      <h1>Dashboard<small>Control panel</small></h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i><strong> Home</strong></a></li>
        <li class="active"><i class="fa fa-user-circle-o" aria-hidden="true"> </i><strong> Manage Order</strong></li>
      </ol>
</section> 

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-success">
				<div class="box-header with-border">
					<h3 class="box-title"><i class="fa fa-list" aria-hidden="true"> </i>    
					Orders List</h3>
				</div>              

              @if(session('successMsg'))
                <div class="alert alert-success alert-dismissible" role="alert">
				  <strong>Success!</strong> - {{session('successMsg')}}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				  </button>
				</div>
              @endif


				<div class="box-body">
					<table id="example1" class="table table-bordered table-striped table-responsive">
						
						<thead>
							<tr>
								<th>Order Id</th>
								<th>Customer Name</th>
								<th>Order Total</th>
								<th>Order Status</th>
								<th>Payment Id</th>
								<th>Transaction Id</th>
								<th>Payment Status</th>
								<th>Invoice</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
						 @foreach($orders as $order)
						    <tr>
						    	<td>{{$order->order_id}}</td>
						    	<td>{{$order->customer_name}}</td>
						    	<td>{{$order->total_amount}}</td>
						    	<td>
						    		@if($order->status==0)
									   <span class="label label-warning">Pending</span>
									@elseif($order->status==1)
									   <span class="label label-info">Processing</span>
									@else 
									   <span class="label label-danger">Delivered</span>
									@endif
						    	</td>
						    	<td>{{$order->payment_id}}</td>
						    	<td>{{$order->transaction_id}}</td>
						    	<td><span class="label label-success">{{$order->payment_status}}
						    	    </span>
						    	</td>
						    	<td>
						    		<a href="{{URL::to('/admin/invoice/'.$order->order_id)}}" class="btn btn-info btn-sm" target="blank">Invoice</a>
						    	</td>
						    	<td>
						    		
								   <a href="{{URL::to('/show_order_details/'.$order->order_id)}}" class="btn btn-warning btn-sm" title="Show Details"><i class="fa fa-eye" aria-hidden="true"></i></a>
									
									 
									<a href="{{route('manage_order.edit',$order->order_id)}}" class="btn btn-info btn-sm" title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

									<form id="delete-form-{{$order->order_id}}" action="{{route('manage_order.destroy',$order->order_id)}}" method="POST" style="display:none">
                                    @csrf
                                    @method('DELETE')	
                                    </form>

									<button class="btn btn-danger btn-sm" title="Delete" onclick="if(confirm('Are you sure you want to delete this slider permanently !!')){
										event.preventDefault();
										document.getElementById('delete-form-{{$order->order_id}}').submit();
									}else{
										event.preventDefault();
									}"><i class="fa fa-trash" aria-hidden="true"></i></button>

						    	</td>
						    </tr>
                         @endforeach
						
							
						
						</tbody>
						
					</table>
				</div>

			</div>
		</div>
	</div>
	
</section>

@endsection

@push('scripts')

<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

@endpush

resources/views/admin/manage_payment.blade.php
@extends('layouts.app')
@section('title','Manage Payment')

@section('content')

<section class="content-header">
      <h1>Dashboard<small>Control panel</small></h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i><strong> Home</strong></a></li>
        <li class="active"><i class="fa fa-rocket" aria-hidden="true"></i><strong> Manage Payment
        </strong></li>
      </ol>
</section> 

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-success">
				<div class="box-header with-border">
					<h3 class="box-title"><i class="fa fa-list" aria-hidden="true"> </i>    
					Orders List</h3>
				</div>              

              @if(session('successMsg'))
                <div class="alert alert-success alert-dismissible" role="alert">
				  <strong>Success!</strong> - {{session('successMsg')}}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				  </button>
				</div>
              @endif


				<div class="box-body">
					<table id="example1" class="table table-bordered table-striped table-responsive">
						
						<thead>
							<tr>
								<th>Payment Id</th>
								<th>Transaction Id</th>
								<th>Payment Type</th>
								<th>Payment Method</th>
								<th>Currency</th>
								<th>Total Amount</th>
								<th>Payment Status</th>
								<th>Recipt</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
					@foreach($payments as $payment)	 
						    <tr>
						    	<td>{{$payment->payment_id}}</td>
						    	<td>{{$payment->transaction_id}}</td>
						    	<td>{{$payment->payment_type}}<br>
                                    ****{{$payment->card_number}}
						    	</td>
						    	<td>{{$payment->payment_method}}</td>
						    	<td>{{$payment->currency}}</td>
						    	<td>{{$payment->amount}}</td>
						    	<td><span class="label label-success">{{$payment->payment_status}}</span></td>
						    	<th>
						    		<a href="{{$payment->receipt_url}}" target="_blank">Print</a>
						    	</th>
						    	<td>
						    		
								   <a href=""  class="btn btn-warning btn-sm " title="Change Status"><i class="fa fa-eye" aria-hidden="true"></i></a>                                   
										 
									<!-- <a href="" class="btn btn-info btn-sm" title="Change Status"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
									 -->
									<form id="delete-form-{{$payment->payment_id}}" action="{{route('manage_payment.destroy',$payment->payment_id)}}" method="POST" style="display:none">
                                    @csrf
                                    @method('DELETE')	
                                    </form>

									<button class="btn btn-danger btn-sm" title="Delete" onclick="if(confirm('Are you sure you want to delete this slider permanently !!')){
										event.preventDefault();
										document.getElementById('delete-form-{{$payment->payment_id}}').submit();
									}else{
										event.preventDefault();
									}"><i class="fa fa-trash" aria-hidden="true"></i></button>

						    	</td>
						    </tr>
                    @endforeach  
												
						</tbody>
						
					</table>
				</div>

			</div>
		</div>
	</div>

</section>


@endsection

@push('scripts')

<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>


<!-- <script>
	
	$(document).ready(function(){

		var table=$('#dataTable').DatatTable();

		table.on('click','.edit',function()){

			$tr = $(this).closest('tr');
			if($($tr).hasClass('child')){
				$tr = $tr.prev('.prent');
			}

			var data=table.row($tr).data();
			console.log(data);

			$('#').val(data[1]);
			$('#').val(data[2]);
			$('#').val(data[3]);
			$('#').val(data[4]);

		$('#editForm').attr('action','/manage_payment/'+data[0]);
		$('#exampleModalLong').modal('show');

		}
	});
</script>
 -->
@endpush