routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//--------------Frontend Pages----------------------


Route::get('/','HomeController@index');
Route::get('/product_by_subcategory/{sub_category_id}','HomeController@product_by_subcategory');

Route::get('/product_by_brand/{brand_name}','HomeController@product_by_brand');
Route::get('/product_details/{product_id}','HomeController@product_details');

//----------------Cart Controller------------------------
Route::post('/add_to_cart','CartController@add_to_cart');
Route::get('/show_cart','CartController@show_cart');
Route::get('/delete_to_cart/{id}','CartController@delete_to_cart');
Route::get('/increment_quantity/{id}','CartController@increment_quantity');
Route::get('/decrement_quantity/{id}','CartController@decrement_quantity');



//-------------------Payment by Authorized.Net---------------------------
Route::get('/payment_by_authorize','PaymentByAuthorizeController@index');
Route::post('/payment_complete','PaymentByAuthorizeController@chargeCreditCard');


//-------------------Payment by paypal-------------------------------------
Route::get('/payment_by_paypal','PaymentByPaypalController@index');
Route::post('/paypal_payment','PaymentByPaypalController@paypal');
Route::get('processPaypal','PaymentByPaypalController@returnPaypal')->name('process.paypal');
Route::get('cancelPaypal','PaymentByPaypalController@cancelPaypal')->name('cancel.paypal');




//-----------------Checkout Controller-----------------

Route::get('/login_check','CheckoutController@login_check');
Route::post('/user_registration','CheckoutController@user_registration');
Route::get('/checkout','CheckoutController@checkout');
Route::post('/shipping_details','CheckoutController@shipping_details');
Route::post('/checkout','CheckoutController@store');


//---------------------user Login and Use Logout-----------------
Route::post('/user_login','CheckoutController@user_login');
Route::get('/user_logout','CheckoutController@user_logout');
Route::get('/payment','CheckoutController@payment');
Route::get('/payment_success','CheckoutController@payment_success');
Route::get('/success_done','CheckoutController@success_done');


//--------------------Some Extra Pages Controller----------------------

Route::get('/show_contact','ExtraPagesController@show_contact');
Route::get('/blog','ExtraPagesController@blog_show');

//------------Backend Pages---------------------------

Route::get('/admin','AdminController@index');
Route::get('/dashboard','SuperAdminController@index');
Route::post('/admin/dashboard','AdminController@dashboard');
Route::get('/show_order_details/{order_id}','AdminController@show_order_details');
Route::get('/admin/invoice/{order_id}','AdminController@invoice');

Route::get('/logout','SuperAdminController@logout');


Route::get('/unactive/{category_id}','StatusController@unactive');
Route::get('/active/{category_id}','StatusController@active');
Route::get('/active_subcategory/{sub_category_id}','StatusController@active_subcategory');
Route::get('/unactive_subcategory/{sub_category_id}','StatusController@unactive_subcategory');

Route::get('/active_product/{product_id}','StatusController@active_product');
Route::get('/unactive_product/{product_id}','StatusController@unactive_product');

Route::get('/unactive_slider/{id}','StatusController@active_slider');
Route::get('/active_slider/{id}','StatusController@unactive_slider');

Route::get('/unactive_brand/{brand_id}','StatusController@active_brand');
Route::get('/active_brand/{brand_id}','StatusController@unactive_brand');

Route::get('/unactive_staff/{id}','StatusController@active_staff');
Route::get('/active_staff/{id}','StatusController@unactive_staff');




Route::get('/show_orderDetails_id/{order_id}','CartController@show_orderDetails_id');

Route::group(['prefix'=>'admin','namespace'=>'admin'],function(){

    
     Route::get('/dashboard','AdminController@index')->name('admin.dashboard');
     Route::resource('category','CategoryController');
     Route::resource('subCategory','SubCategoryController');
     Route::resource('products','ProductController');
     Route::resource('slider','SliderController');
     Route::resource('brand','BrandController');
     Route::resource('blog','BlogController');
     Route::resource('staff','StaffController');
     Route::resource('manage_order','ManageOrderController');
     Route::resource('manage_payment','ManagePaymentController');

    


});

app/Http/Controllers/Admin/StaffController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $staffs=DB::table('tbl_staffs')
               ->get();

        return view('admin.staff.index',compact('staffs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.staff.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[

         'name'=>'required',
         'email'=>'required',
         'address'=>'required',
         'area'=>'required',
         'mobile_number'=>'required',
         'image'=>'required |image| mimes:jpeg,png,jpg,gif,svg'

         ]);

        $data=$request->all();

        
        $data=array();
        $data['name']=$request->name;
        $data['email']=$request->email;
        $data['address']=$request->address;
        $data['area']=$request->area;
        $data['mobile_number']=$request->mobile_number;
        $data['publication_status']=$request->publication_status;

        $image=$request->file('image');
        if (isset($image)) {
            
            $image_name=$image->getClientOriginalName();
            $image_ext=strtolower($image->getClientOriginalExtension());
            $image_full_name=$image_name.'-'.uniqid().'.'.$image_ext;

            if (!file_exists('upload/staff')) {
                
                mkdir('upload/staff',0777,true);
            }

            $success=$image->move('upload/staff',$image_full_name);
            if ($success) {
               $data['image']=$image_full_name;
             
            }
                          
          }
          
    DB::table('tbl_staffs')->insert($data);
return redirect()->route('staff.index')->with('successMsg','Data is Updated Successfully !!');

        /*print_r($data);*/
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $staff=DB::table('tbl_staffs')
               ->where('id',$id)
               ->first();
        return view('admin.staff.edit',compact('staff'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[

         'name'=>'required',
         'email'=>'required',
         'address'=>'required',
         'area'=>'required',
         'mobile_number'=>'required',
         'image'=>'required|sometimes|image|mimes:jpeg,png,jpg,gif,svg'

         ]);


        $data=array();
        $data['name']=$request->name;
        $data['email']=$request->email;
        $data['address']=$request->address;
        $data['area']=$request->area;
        $data['mobile_number']=$request->mobile_number;
        /*$data['publication_status']=$request->publication_status;*/

        $staff=DB::table('tbl_staffs')
               ->where('id',$id)
               ->first();

        $image=$request->file('image');
        if (isset($image)) {
            
            $image_name=$image->getClientOriginalName();
            $image_ext=strtolower($image->getClientOriginalExtension());
            $image_full_name=$image_name.'-'.uniqid().'.'.$image_ext;

            if (!file_exists('upload/staff')) {
                
                mkdir('upload/staff',0777,true);
            }

            $success=$image->move('upload/staff',$image_full_name);
            if($success) {
               $data['image']=$image_full_name;
             
            }else{
                $data['image']=$staff->image;
            }
                          
          }
          
    DB::table('tbl_staffs')->update($data);
return redirect()->route('staff.index')->with('successMsg','Data is Edited Successfully !!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $staff=DB::table('tbl_staffs')
               ->where('id',$id)
               ->first();
             

       if(file_exists('upload/staff/'.$staff->image)) {
           unlink('upload/staff/'.$staff->image);           
       }
       DB::table('tbl_staffs')->where('id',$id)->delete();

       return redirect()->route('staff.index')->with('successMsg','Staff is deleted successfully !!');
    }
}

resources/views/admin/staff/create.blade.php
@extends('layouts.app')

@section('title','Add Staff')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-user-circle-o" aria-hidden="true"></i> All Staff</li>
      </ol>
</section> 

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-success">
				<div class="box-header with-border">
	              <h3 class="box-title">Add Staff</h3>
	              
	              <div class="box-tools pull-right">
	                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
	                </button>
	               
	                <button type="button" class="btn btn-box-tool" data-toggle="dropdown">
	                    <i class="fa fa-wrench"></i></button>
	                              
	                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
	              </div>
	            </div>
            <!-- /.box-header -->
            <form class="form-horizontal" action="{{route('staff.store')}}" method="POST" enctype="multipart/form-data">
            	@csrf
            	<div class="box-body">
            		<div class="row">
            			<div class="col-md-8">

            				<div class="form-group">
			                  <label for="Staff Name" class="col-sm-4 control-label">Name</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" id="name" placeholder="Enter Staff Name" name="name">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="Staff Email" class="col-sm-4 control-label">Email</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" id="email" placeholder="Enter Staff Email" name="email">
			                  </div>
			                </div>

			                <div class="form-group hidden-phone">
			                  <label for="Address" class="col-sm-4 control-label">Address</label>

			                  <div class="col-sm-8">
			                      <textarea class="textarea" name="address" 
		                      style="width: 100%; height: 60px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
		                      	
		                         </textarea>
			                  </div>
			                </div>
			                <div class="form-group">
			                  <label for="Delivary Area" class="col-sm-4 control-label">Delivary Area</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" id="area" placeholder="Enter Staff Delivary Area" name="area">
			                  </div>
			                </div>
			                <div class="form-group">
			                  <label for="Staff Mobile" class="col-sm-4 control-label">Mobile Number</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" id="mobile" placeholder="Enter Staff Mobile Number" name="mobile_number">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="Image" class="col-sm-4 control-label">Image</label>

			                  <div class="col-sm-8">
			                    <input type="file" class="input-file uniform-on form-control" id="fileInput" name="image">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="publication_status" class="col-sm-4 control-label">Publication Status</label>

			                  <div class="col-sm-8">
			                    <input type="checkbox" name="publication_status" value="1">
			                  </div>
			                </div>
            				
            			</div>
            		</div>
            	</div>
            	<div class="box-footer">
            		<div class="row">
            			<div class="col-md-8">
            				<button type="submit" class="btn btn-primary pull-right">  Submit
                	       </button>

		                	<button type="reset" class="btn btn-default">Cancel
		                	</button>
            			</div>
            		</div>
            	</div>
            </form>
			</div>
		</div>
	</div>
</section>

@endsection

resources/views/admin/staff/edit.blade.php
@extends('layouts.app')

@section('title','Add Staff')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-user-circle-o" aria-hidden="true"></i> All Staff</li>
      </ol>
</section> 

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-success">
				<div class="box-header with-border">
	              <h3 class="box-title">Add Staff</h3>
	              
	              <div class="box-tools pull-right">
	                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
	                </button>
	               
	                <button type="button" class="btn btn-box-tool" data-toggle="dropdown">
	                    <i class="fa fa-wrench"></i></button>
	                              
	                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
	              </div>
	            </div>
            <!-- /.box-header -->
            <form class="form-horizontal" action="{{route('staff.update',$staff->id)}}" method="POST" enctype="multipart/form-data">
            	@csrf
            	@method('put')
            	<div class="box-body">
            		<div class="row">
            			<div class="col-md-8">

            				<div class="form-group">
			                  <label for="Staff Name" class="col-sm-4 control-label">Name</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" value="{{$staff->name}}" name="name">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="Staff Email" class="col-sm-4 control-label">Email</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" value="{{$staff->email}}" name="email">
			                  </div>
			                </div>

			                <div class="form-group hidden-phone">
			                  <label for="Address" class="col-sm-4 control-label">Address</label>

			                  <div class="col-sm-8">
			                      <textarea class="textarea" name="address" 
		                      style="width: 100%; height: 60px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{$staff->address}}
		                      	
		                         </textarea>
			                  </div>
			                </div>
			                <div class="form-group">
			                  <label for="Delivary Area" class="col-sm-4 control-label">Delivary Area</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" value="{{$staff->area}}" name="area">
			                  </div>
			                </div>
			                <div class="form-group">
			                  <label for="Staff Mobile" class="col-sm-4 control-label">Mobile Number</label>

			                  <div class="col-sm-8">
			                    <input type="text" class="form-control" value="{{$staff->mobile_number}}" name="mobile_number">
			                  </div>
			                </div>

			                <div class="form-group">
			                	<label for="Image" class="col-sm-4 control-label">Old Image</label>
			                   <div class="col-sm-8">
			                      <img src="{{asset('upload/staff/'.$staff->image)}}" style="width:100px;height:70px;">
			                  </div>
			                </div>

			                <div class="form-group">
			                  <label for="Image" class="col-sm-4 control-label">New Image</label>

			                  <div class="col-sm-8">
			                    <input type="file" class="input-file uniform-on form-control" id="fileInput" name="image">
			                  </div>
			                </div>
           				
            			</div>
            		</div>
            	</div>
            	<div class="box-footer">
            		<div class="row">
            			<div class="col-md-8">
            				<button type="submit" class="btn btn-primary pull-right">  Submit
                	       </button>

		                	<button type="reset" class="btn btn-default">Cancel
		                	</button>
            			</div>
            		</div>
            	</div>
            </form>
			</div>
		</div>
	</div>
</section>

@endsection

resources/views/admin/staff/index.blade.php
@extends('layouts.app')
@section('title','All Staff')

@section('content')

<section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><i class="fa fa-user-circle-o" aria-hidden="true"> </i> All Staff</li>
      </ol>
</section> 

<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-success">
				<div class="box-header with-border">
					<h3 class="box-title">Slider List</h3>
				</div>              

              @if(session('successMsg'))
                <div class="alert alert-success alert-dismissible" role="alert">
				  <strong>Success!</strong> - {{session('successMsg')}}
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				  </button>
				</div>
              @endif


				<div class="box-body">
					<table id="example1" class="table table-bordered table-striped table-responsive">
						
						<thead>
							<tr>
								<th>Name</th>
								<th>Image</th>
								<th>Email</th>
								<th>Address</th>
								<th>Area</th>
								<th>Mobile Number</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
						</thead>

						<tbody>
							<tr>
						@foreach($staffs as $key=>$staff)		
								<td>{{$staff->name}}</td>
								<td><img src="{{asset('upload/staff/'.$staff->image)}}" style="width:100px;height:70px;"></td>
								<td>{{$staff->email}}</td>
								<td>{{$staff->address}}</td>
								<td>{{$staff->area}}</td>
								<td>{{$staff->mobile_number}}</td>
								
								<td>
									@if($staff->publication_status==1)
									   <span class="label label-success">Active</span>
									@else 
									   <span class="label label-danger">Unctive</span>
									@endif
								</td>
								<td>
									@if($staff->publication_status==1)
									  <a href="{{URL::to('/unactive_staff/'.$staff->id)}}" class="btn btn-danger btn-sm"><i class="fa fa-thumbs-down" aria-hidden="true"></i></a>
									@else 
									  <a href="{{URL::to('/active_staff/'.$staff->id)}}" class="btn btn-success btn-sm"><i class="fa fa-thumbs-up" aria-hidden="true"></i></a>
									@endif

									<a href="{{route('staff.edit',$staff->id)}}" class="btn btn-info btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                     
                                    <form id="delete-form-{{$staff->id}}" action="{{route('staff.destroy',$staff->id)}}" method="POST" style="display:none">
                                    @csrf
                                    @method('DELETE')	
                                    </form>

									<button class="btn btn-danger btn-sm" onclick="if(confirm('Are you sure you want to delete this slider permanently !!')){
										event.preventDefault();
										document.getElementById('delete-form-{{$staff->id}}').submit();
									}else{
										event.preventDefault();
									}"><i class="fa fa-trash" aria-hidden="true"></i></button>
								</td>
							
							</tr>
							@endforeach	
						</tbody>
						
					</table>
				</div>

			</div>
		</div>
	</div>
	
</section>

@endsection

@push('scripts')

<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

@endpush